ports:
  - port: 8080
    onOpen: open-preview

tasks:
  - init: ./mvnw package -DskipTests

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot