name: Gitpod CDE on new issue

on: 
  issues:
    types: [opened]

jobs:
  gitpod-workspace-creation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Gitpod CLI
      run: |
        wget -O gitpod https://gitpod.io/static/bin/gitpod-cli-linux-amd64
        chmod +x gitpod
        ./gitpod login --token ${{ secrets.GITPOD_TOKEN }} --org ${{ secrets.GITPOD_ORG }}
        
    - name: Create a Gitpod workspace
      uses: actions/github-script@v5
      with:
        script: |
          const issueNumber = context.issue.number;
          const WORKSPACE_URL=$(./gitpod ws create github.com/${context.repo.owner}/${context.repo.repo}/issues/${issueNumber} --dont-wait);
          const message = `Hi! Thanks for raising this issue, a Gitpod workspace is being prepared for you. Open to contribute: [![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](${WORKSPACE_URL})`;
          github.rest.issues.createComment({
            issue_number: issueNumber,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          });
