name: Dev Workflow

on: [push, pull_request]

jobs:
  gitpod-workspace-creation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Gitpod CLI
      run: |
        wget -O gitpod https://gitpod.io/static/bin/gitpod-cli-linux-amd64
        chmod +x gitpod
        ./gitpod login --token ${{ secrets.GITPOD_TOKEN }} --org ${{ secrets.GITPOD_ORG }}

    - name: Create Gitpod Workspace
      run: |
        WORKSPACE_ID=$(./gitpod ws create gitlab.com/pawlean/spring-boot-with-gitpod-cli --dont-wait)
        echo "WORKSPACE_ID=$WORKSPACE_ID" >> $GITHUB_ENV
        echo $WORKSPACE_ID

    - name: Set up Job Summary
      if: success()
      run: echo "Gitpod Workspace URL: https://gitpod.io/start/#$WORKSPACE_ID" >> $GITHUB_ENV
