name: Gitpod CDE on push / PR

on: 
  issues:
    types: [opened]

jobs:
  gitpod-workspace-creation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Gitpod CLI
      run: |
        wget -O gitpod https://gitpod.io/static/bin/gitpod-cli-linux-amd64
        chmod +x gitpod
        ./gitpod login --token ${{ secrets.GITPOD_TOKEN }} --org ${{ secrets.GITPOD_ORG }}

    - name: Create Gitpod Workspace
      run: |
        WORKSPACE_ID=$(./gitpod ws create github.com/pawlean/spring-boot-with-gitpod-cli --dont-wait)

    - name: Comment on new issue
      uses: actions/github-script@v5
      with:
        script: |
          const issueNumber = context.issue.number;
          const gitpodUrl = `https://gitpod.io/new/?autostart=true##https://github.com/${context.repo.owner}/${context.repo.repo}/issues/${issueNumber}`;
          const message = `Hello 👋, a Gitpod workspace is being prepared for you. Open to contribute: ${gitpodUrl}`;
          github.rest.issues.createComment({
            issue_number: issueNumber,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          });
