name: Gitpod CDE on push / PR

on: [push, pull_request]

jobs:
  gitpod-workspace-creation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Gitpod CLI
      run: |
        wget -O gitpod https://gitpod.io/static/bin/gitpod-cli-linux-amd64
        chmod +x gitpod
        ./gitpod login --token ${{ secrets.GITPOD_TOKEN }} --org ${{ secrets.GITPOD_ORG }}

    - name: Create Gitpod Workspace
      run: |
        WORKSPACE_ID=$(./gitpod ws create github.com/pawlean/spring-boot-with-gitpod-cli --dont-wait)
